[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# Security headers
[[headers]]
for = "/*"
  [headers.values]
  
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "no-referrer"

# Redirect all routes to root (for SPAs)
[[redirects]]
  from = "/*"
  to = "/"
  status = 200

# Netlify plugin for Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

